CREATE TABLE IF NOT EXISTS news
(post_id INTEGER PRIMARY KEY AUTOINCREMENT,
text TEXT,
dt DATE,
img BLOB DEFAULT NULL);

CREATE TABLE IF NOT EXISTS pictures
(pic_id INTEGER PRIMARY KEY AUTOINCREMENT,
text TEXT,
dt DATE,
img BLOB DEFAULT NULL);

CREATE TABLE IF NOT EXISTS siteinfo
(photo BLOB DEFAULT NULL);,
description TEXT,
email TEXT,
phone TEXT);

CREATE TABLE IF NOT EXISTS users
(user_id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
psw TEXT NOT NULL);

INSERT INTO users VALUES (1, 'ponomarev_admin', 'e13a900d88627e0edce0389e8c887ee0');
